"""Update simulation_updates table

Revision ID: 9417248c23e9
Revises: 
Create Date: 2024-10-16 08:50:14.742283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9417248c23e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_updates', sa.Column('update_content', sa.Text(), nullable=False))
    op.drop_column('simulation_updates', 'thread_id')
    op.drop_column('simulation_updates', 'water_level')
    op.drop_column('simulation_updates', 'resources')
    op.drop_column('simulation_updates', 'population')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_updates', sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulation_updates', sa.Column('resources', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('simulation_updates', sa.Column('water_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('simulation_updates', sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('simulation_updates', 'update_content')
    # ### end Alembic commands ###
